"""add_snatch_rules_to_system_settings

Revision ID: 17dfe90825b6
Revises: 9575f04bc189
Create Date: 2025-12-23 10:47:50.494100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17dfe90825b6'
down_revision: Union[str, None] = '9575f04bc189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('snatch_rules', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'snatch_rules')
    # ### end Alembic commands ###
