"""add_update_time_to_system_settings

Revision ID: 9575f04bc189
Revises: 
Create Date: 2025-12-23 09:43:27.991087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9575f04bc189'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加为可空列
    op.add_column('system_settings', sa.Column('update_time', sa.BigInteger(), nullable=True))
    
    # 更新现有记录的 update_time 为当前时间戳
    import time
    current_timestamp_ms = int(time.time() * 1000)
    op.execute(f"UPDATE system_settings SET update_time = {current_timestamp_ms} WHERE update_time IS NULL")
    
    # 再将列设置为非空
    op.alter_column('system_settings', 'update_time', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'update_time')
    # ### end Alembic commands ###
