"""add_debate_voting_system_models

Revision ID: debate_voting_001
Revises: 17dfe90825b6
Create Date: 2025-01-13 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'debate_voting_001'
down_revision: Union[str, None] = '17dfe90825b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 添加新的用户角色
    op.execute("ALTER TYPE userrole ADD VALUE 'judge'")
    op.execute("ALTER TYPE userrole ADD VALUE 'audience'")
    
    # 为User表添加辩论赛专用字段
    op.add_column('users', sa.Column('debater_position', sa.String(50), nullable=True))
    op.add_column('users', sa.Column('team_side', sa.String(10), nullable=True))
    
    # 创建contests表
    op.create_table('contests',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('class_id', sa.Integer(), nullable=False),
        sa.Column('topic', sa.String(500), nullable=False),
        sa.Column('pro_team_name', sa.String(100), nullable=False),
        sa.Column('con_team_name', sa.String(100), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 创建vote_records表
    op.create_table('vote_records',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('contest_id', sa.Integer(), nullable=False),
        sa.Column('voter_id', sa.Integer(), nullable=False),
        sa.Column('team_side', sa.String(10), nullable=False),
        sa.Column('vote_phase', sa.String(20), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
        sa.ForeignKeyConstraint(['voter_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 创建judge_scores表
    op.create_table('judge_scores',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('contest_id', sa.Integer(), nullable=False),
        sa.Column('judge_id', sa.Integer(), nullable=False),
        sa.Column('debater_id', sa.Integer(), nullable=False),
        sa.Column('language_expression', sa.Float(), nullable=False),
        sa.Column('logical_reasoning', sa.Float(), nullable=False),
        sa.Column('debate_skills', sa.Float(), nullable=False),
        sa.Column('quick_response', sa.Float(), nullable=False),
        sa.Column('overall_awareness', sa.Float(), nullable=False),
        sa.Column('general_impression', sa.Float(), nullable=False),
        sa.Column('total_score', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
        sa.ForeignKeyConstraint(['judge_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['debater_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 添加新的系统阶段枚举值
    op.execute("ALTER TYPE systemstage ADD VALUE 'PRE_VOTING'")
    op.execute("ALTER TYPE systemstage ADD VALUE 'DEBATE_IN_PROGRESS'")
    op.execute("ALTER TYPE systemstage ADD VALUE 'POST_VOTING'")
    op.execute("ALTER TYPE systemstage ADD VALUE 'JUDGE_SCORING'")
    op.execute("ALTER TYPE systemstage ADD VALUE 'RESULTS_SEALED'")
    op.execute("ALTER TYPE systemstage ADD VALUE 'RESULTS_REVEALED'")
    
    # 为system_settings表添加辩论赛专用字段
    op.add_column('system_settings', sa.Column('contest_id', sa.Integer(), nullable=True))
    op.add_column('system_settings', sa.Column('pre_voting_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('system_settings', sa.Column('post_voting_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('system_settings', sa.Column('judge_scoring_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('system_settings', sa.Column('results_revealed', sa.Boolean(), nullable=False, server_default='false'))
    
    op.create_foreign_key('fk_system_settings_contest', 'system_settings', 'contests', ['contest_id'], ['id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除外键约束
    op.drop_constraint('fk_system_settings_contest', 'system_settings', type_='foreignkey')
    
    # 删除system_settings表的新字段
    op.drop_column('system_settings', 'results_revealed')
    op.drop_column('system_settings', 'judge_scoring_enabled')
    op.drop_column('system_settings', 'post_voting_enabled')
    op.drop_column('system_settings', 'pre_voting_enabled')
    op.drop_column('system_settings', 'contest_id')
    
    # 删除新表
    op.drop_table('judge_scores')
    op.drop_table('vote_records')
    op.drop_table('contests')
    
    # 删除users表的新字段
    op.drop_column('users', 'team_side')
    op.drop_column('users', 'debater_position')
    
    # ### end Alembic commands ###